---
 - hosts: digital_ocean_box
   sudo: true
   remote_user: root

   vars_files:
    - "{{ CONFIG_FILE_PATH }}"

   roles:
    - common
    - postgres
    - nginx
    - ferm
    - docker
#    - coracle
    - objective8_postgres_config
    - objective8_postgres_backups
    - objective8_application_config
