# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.box = "ubuntu/trusty64"

  config.vm.network "private_network", ip: "192.168.50.50"
  config.vm.network :forwarded_port, guest: 22, host: 2222, id: "ssh", auto_correct: false

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "development_playbook.yml"
    ansible.inventory_path = "development.inventory"
    ansible.sudo = true
    ansible.ask_sudo_pass = true
  end

end

